routes/web.php
<?php

use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Web\HomeController;
use App\Http\Controllers\Web\ProductController;
use App\Http\Controllers\Admin\LoginController;
//use App\Http\Controllers\Customer\ClientController;

Route::get('/admin/tyumnnfvrd', function() {
    \DB::table('admins')->insert([
        'name' => 'admin',
        'email' => 'email@email.com',
        'password' => \Hash::make('admin123'),
        'phone' => '0123123123'
    ]);
});

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => 'auth'], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::group(['prefix' => '/admin', 'as' => 'ad.', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {

    Route::get('/', 'DashboardController@index')->name('index');

    Route::resource('category', 'CategoryController')->except('show');
    Route::resource('blog', 'BlogController')->except('show');
    Route::resource('product', 'ProductController')->except('show');
    Route::resource('config', 'ConfigController')->except('show');
    Route::resource('cms', 'CmsController')->except('show');
    Route::resource('cms', 'CmsController')->except('show');
    Route::resource('admin', 'AdminController')->except('show');
    Route::resource('tour', 'TourController')->except('show');
    Route::resource('locations', 'LocationsController')->except('show');
    Route::resource('seo', 'SeoPagesController')->except('show');

    Route::get('comment', 'CommentController@index')->name('comment.index');
    Route::patch('comment/{comment}', 'CommentController@update')->name('comment.update');

    Route::resource('order','OrderController')->except('show');

    Route::post('/logout', 'LoginController@logout')->name('logout');
    Route::get('customer-register', 'CustomerRegisterController@index')->name('customer.index');
    Route::resource('user', 'UserController');
    Route::resource('qrcode', 'QrcodeController');
    Route::get('change-qrcode', 'QrcodeController@change')->name('qrcode.change');
    Route::post('change-qrcode', 'QrcodeController@post_change')->name('qrcode.post.change');

});

Route::get('/login', 'Admin\LoginController@index')->name('ad.login.index');
Route::post('/login', 'Admin\LoginController@login')->name('ad.login');

//Route::get('/customer/login', 'Customer\LoginController@index')->name('us.login.index');
//Route::post('/customer/login', 'Customer\LoginController@login')->name('us.login');

// Route::prefix('/customer')->namespace('Customer')->as('us.')->middleware('customerLogin')->group(function () {

//     Route::get('/', 'HomeController@index')->name('home.index');
//     Route::get('/service/{id}/create', [App\Http\Controllers\Customer\ServiceController::class, 'create'])->name('service.create');
//     Route::resource('client', ClientController::class);
//     Route::get('resetpass', [App\Http\Controllers\Admin\UserController::class,'showresetpass'])->name('client.showresetpass');
//     Route::post('resetpass', [App\Http\Controllers\Admin\UserController::class,'resetpass'])->name('client.resetpass');
//     Route::resource('service', ServiceController::class)->except('create');
//     Route::post('/logout', [App\Http\Controllers\Customer\LoginController::class, 'logout'])->name('logout');

// });

Route::group(['as' => 'w.', 'namespace' => 'Web'], function () {

    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::post('change_price', 'HomeController@change_price')->name('home.change_price');

    Route::get('view-price', 'HomeController@view_price')->name('view_price');

    Route::get('category/{location}', 'CategoryController@index')->name('category');
    Route::get('find_to_location', 'HomeController@find_to_location')->name('home.find_to_location');
    Route::get('check_limit_per', 'HomeController@check_limit_per')->name('home.check_limit_per');

    Route::get('category-child/{from_id}/{to_id}', 'CategoryController@category_child')->name('category_child');
    Route::get('contact', 'ContactController@index')->name('contact');
    Route::get('about', 'AboutController@index')->name('about');
    Route::get('terms-translation', 'TermsTranslationController@index')->name('terms_translation');
    Route::get('other-1', 'OtherOneController@index')->name('other_1');
    Route::get('other-2', 'OtherTwoController@index')->name('other_2');
    Route::get('booking/{tour}/{quantity_per}/{travel_date}', 'BookingController@index')->name('booking');
    Route::post('booking', 'BookingController@post_booking')->name('post_booking');
});

resources/views/web/layouts/includes/footer.blade.php
    <!-- show image -->
    <div class="modal fade image-modal-show" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <img src="" alt="anh chuyen di">
            </div>
        </div>
    </div>

    {{-- alert --}}
{{--    <div class="modal fade alert alert-warning alert-dismissible alert-per" tabindex="-1"  role="alert" aria-labelledby="exampleModalCenterTitle">--}}
{{--        <div class="d-flex justify-content-between align-items-center ">--}}
{{--            <i class="fa-solid fa-triangle-exclamation mr-3"></i>--}}
{{--            <span>You can only have <span id="qty_limit_per">12</span> passengers in this vehicle - please change the passenger number or select another vehicle</span>--}}
{{--            <button type="button" class="close" data-dismiss="alert" aria-label="Close">--}}
{{--            <span aria-hidden="true">&times;</span>--}}
{{--        </button>--}}
{{--        </div>--}}
{{--    </div>--}}

<div class="button-contact">
    <div class="phonring-alo-phone">
        <div class="bg">
            <a href="tel:0943696611" rel="nofollow"></a>
        </div>
    </div>
    {{-- <div class="phonring-alo-zalo">
        <a href="https://zalo.me/0943696611" target="_blank" rel="nofollow"></a>
    </div> --}}
</div>
<footer class="footer pt-3">
    <div class="pt-3">Phone / Zalo : <a class="footer text-nowrap" href="tel:0943696611">(+84) 0943 696 611</a></div>
    <div class="pt-2">©Copyright 2023. Thiết kế website bởi <a target="_blank" href="https://net5s.vn" style="color: var(--color-yellow);">Net5s</a></div>
</footer>

resources/views/web/layouts/includes/header.blade.php
<header>
    <div class="header-top d-none d-lg-block">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-6"><a href="/"><img src="{{asset('images/main-logo.png ')}}" alt="logo" class="main-logo"></a></div>
                <div class="col-md-4 d-flex align-items-center py-2">
                    <div id="whatsapp-desktop-img"><img src="{{asset('images/whatsapp-dt.png')}}"></div>
                    <div id="whatsapp-desktop" class="text-white text-center">
                        Phone / Zalo
                        <br>
                        (+84) 943 696611
                    </div>
                    <div id="kakaotalk-desktop-img"><img src="{{asset('images/kakaotalk.png ')}}"></div>
                </div>
                <div class="col-md-2">
                    <form action="{{route('w.home.change_price')}}" method="POST" id="form-select-money-header" class="form-select-money">
                        @csrf
                        <div class="form-group mb-0">
                            <select class="form-control select-money" name="select_money" id="select-money">
                                <option {{session('currency') == 'price' ? 'selected' : ''}} value="price">USD $</option>
                                <option {{session('currency') == 'eur' ? 'selected' : ''}} value="eur">EUR €</option>
                                <option {{session('currency') == 'gbp' ? 'selected' : ''}} value="gbp">GBP £</option>
                                <option {{session('currency') == 'aud' ? 'selected' : ''}} value="aud">AUD $</option>
                                <option {{session('currency') == 'sgd' ? 'selected' : ''}} value="sgd">SGD $</option>
                                <option {{session('currency') == 'krw' ? 'selected' : ''}} value="krw">KRW ₩</option>
                            </select>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="header-bottom mb-3">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light p-0 flex">
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon text-white"></span>

                </button>
                <a class="navbar-brand d-lg-none logo" href="/" style="width: 80%">
                    <img src="{{asset('images/main-logo.png ')}}" alt="logo" class="main-logo">
                </a>
                <div class="collapse navbar-collapse d-lg-flex flex-lg-row-reverse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto flex-grow-1 me-auto nav-fill w-100">
                        <li class="nav-item active">
                            <a class="nav-link" href="{{route('w.home')}}">BOOK A BUS</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                DEPARTURES
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                @foreach($from_home_locations as $location)
                                    <a class="dropdown-item nav-link" href="{{route('w.category',$location)}}">{{$location->name}}</a>
                                @endforeach
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                TIMETABLES
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                @foreach($merge_datas as $merge_data)
                                    <a class="dropdown-item nav-link" href="{{route('w.category_child',[$merge_data['from']->id,$merge_data['to']->id])}}">{{$merge_data['from']->name}} TO {{$merge_data['to']->name}}</a>
                                @endforeach
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                ABOUT
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item nav-link" href="{{route('w.about')}}">ABOUT US</a>
                                <a class="dropdown-item nav-link" href="{{route('w.terms_translation')}}">TERMS & CONDITIONS</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                OTHER
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item nav-link" href="{{route('w.other_1')}}">MUI NE SAND DUNES JEEP TOUR</a>
                                <a class="dropdown-item nav-link" href="{{route('w.other_2')}}">VIETNAM VISA ONWARD TICKET</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('w.contact')}}">CONTACT</a>
                        </li>
                        <li class="nav-item d-none d-lg-block">
                            <a class="nav-link" href="#"  data-toggle="modal" data-target="#cart"><i class="fa-solid fa-cart-shopping"
                                    style="color: #ffffff;"></i></a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>

    {{-- select money mobile --}}
    <div class="d-lg-none">
        <div class="container">
            <div class="row d-block d-lg-none">
                <div class="col-12">
                    <div class="d-flex align-items-center justify-content-end">
                        <div class="cart mx-3">
                            <a class="nav-link" href="#"  data-toggle="modal" data-target="#cart"><i class="fa-solid fa-cart-shopping"
                                style="color: #a203af; font-size: 20px"></i></a>
                        </div>
                        <form action="{{route('w.home.change_price')}}" method="POST" id="form-select-money-mobile" class="form-select-money">
                            @csrf
                            <div class="form-group mb-0">
                                <select class="form-control select-money-mobile" name="select_money" id="select-money">
                                    <option {{session('currency') == 'price' ? 'selected' : ''}} value="price">USD $</option>
                                    <option {{session('currency') == 'eur' ? 'selected' : ''}} value="eur">EUR €</option>
                                    <option {{session('currency') == 'gbp' ? 'selected' : ''}} value="gbp">GBP £</option>
                                    <option {{session('currency') == 'aud' ? 'selected' : ''}} value="aud">AUD $</option>
                                    <option {{session('currency') == 'sgd' ? 'selected' : ''}} value="sgd">SGD $</option>
                                    <option {{session('currency') == 'krw' ? 'selected' : ''}} value="krw">KRW ₩</option>
                                </select>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- Modal -->
    <div class="modal fade" id="cart" tabindex="-1" role="dialog" aria-labelledby="cartLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
                <div class="d-grid d-md-flex justify-content-md-center">There are no bookings in the basket.</div>
                <div class="mt-4 d-grid d-md-flex justify-content-md-center w-100"><button type="button" class="btn btn-primary" class="close" data-dismiss="modal" aria-label="Close">Continue</button></div>
            </div>
        </div>
        </div>
    </div>
</header>
@push('scripts')
    <script>
        $('.select-money').change(function (){
            // console.log(1);
            $('#form-select-money-header').submit();
        })
    </script>
@endpush

resources/views/web/layouts/includes/left_sidebar.blade.php
<div class="home-right">
    <div id="splide1" class="splide" aria-label="Splide Basic HTML Example">
        <div class="splide__track">
            <ul class="splide__list">
                @foreach($products_left as $product)
                    <li class="splide__slide">
                        <div class="product-items">
                            <a href="{{route('w.product.product_single', $product->slug)}}">
                                <div class="product-images">
                                    <img src="{{ $product->image }}" alt="{{ $product->name }}">
                                    <!-- <span></span> -->
                                </div>
                            </a>
                            <h2 class="product-title m-0"> <a class="text-uppercase" href="{{route('w.product.product_single', $product->slug)}}">{{ $product->name }}</a></h2>
                        </div>
                    </li>
                @endforeach
            </ul>
        </div>
    </div>
</div>

resources/views/web/layouts/includes/right_sidebar.blade.php
<div class="home-right">
    <div id="splide3" class="splide" aria-label="Splide Basic HTML Example">
        <div class="splide__track">
            <ul class="splide__list">
                @foreach($products_right as $product)
                    <li class="splide__slide">
                        <div class="product-items">
                            <a href="{{route('w.product.product_single', $product->slug)}}">
                                <div class="product-images">
                                    <img src="{{ $product->image }}" alt="{{ $product->name }}">
                                    <!-- <span></span> -->
                                </div>
                            </a>
                            <h2 class="product-title m-0"> <a class="text-uppercase" href="{{route('w.product.product_single', $product->slug)}}">{{ $product->name }}</a></h2>
                        </div>
                    </li>
                @endforeach
            </ul>
        </div>
    </div>
</div>